name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This invokes the `version` script in `package.json`, which will run
          # `changeset version` and then `yarn`. We need to run `yarn` in order
          # to update `yarn.lock`:  https://github.com/changesets/action/issues/170
          version: yarn version
          # This invokes the `release` script in `package.json`, which will build
          # all the packages and then invoke `changeset publish`.
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This token was generated by Nathan Walters on 2024-06-17.
          # It expires on 2030-01-01.
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
